### ISSUE TITLE
Only push changes out to X-Touch

### ISSUE THREAD

**Issue by ollie-nye** [ollie-nye/vban-xctrl#2]
Pushing a full state update to the X-Touch with every received VBAN packet can cause some faders to 'rattle' in place, depending on their level. This can't be good for the motors or faders, so reducing this rate of change to as slow as possible while still maintaining responsiveness sounds like a good idea.

**Comment by Golstrider** [comment]
Hi, it's golstrider from Reddit 

Ok. This fix has worked. Now faders are not going crazy :)

Another issue arises when I physically move faders or push some buttons in MC mode. Sometimes (I didn't catch up when exactly), this affects values in Voicemeeter. So, for example, I lower a first track fader on -5db, then switch to Voicemeeter mode, and see that strip of my first input snack down on several db too.

So when I switch to the DAW and come back to VoiceMeeter, faders go onto start to -∞ position. So after I push the fader bank button and switch, for example, to the "output" layer (here, the faders come to the right position) and move back to the "input" layer, the faders get the right position. I guess, When I switch between the XCtrl and Mackie modes, the faders don't get the values from the voicemeeter.

Another issue arises when I physically move faders or push some buttons in MC mode. Sometimes (I didn't catch up when exactly), this affects values in Voicemeeter. So, for example, I lower a first track fader on -5db, then switch to Voicemeeter mode, and see that strip of my first input snack down on several db too.
