### ISSUE TITLE
Increase more amount segments of the indicator scale

### ISSUE THREAD

**Issue by Golstrider** [ollie-nye/vban-xctrl#5]
When the signal is peaking, the physical indicator uses only 6 segments instead of 8 to show the signal.
![IMG_20220910_135706](https://user-images.githubusercontent.com/83399287/189480343-cb52784b-9d03-4972-afbd-ca9c00da0fac.jpg)

**Comment by JoshMiles** [comment]
Just bumping this as I'm experiencing the same bug (:

**Comment by ollie-nye** [comment]
Finally got round to fixing this one! Updated in [0393a7a](https://github.com/ollie-nye/vban-xctrl/commit/0393a7af83f3e5591c1b6cb10d70d66d29e4b5c8), should be working on the full range now if you pull the latest changes

**Comment by Golstrider** [comment]
> Finally got round to fixing this one! Updated in [0393a7a](https://github.com/ollie-nye/vban-xctrl/commit/0393a7af83f3e5591c1b6cb10d70d66d29e4b5c8), should be working on the full range now if you pull the latest changes

Hi! Thanks for the update!
Just checked it twice, and unfortunately, there are only 7 segments works instead of 8, and they starting to get red color on the 5th segment and above. But the only two last segments should have red color, or am I wrong?

**Comment by ollie-nye** [comment]
It seems to be working alright here, have to properly overdrive a channel to get the last segment lit though! The XTouch has the first four as green, the next three as orange and the final one as red, unfortunately they're just the led colors, we can't change them on this board

**Comment by Golstrider** [comment]
> It seems to be working alright here, have to properly overdrive a channel to get the last segment lit though! The XTouch has the first four as green, the next three as orange and the final one as red, unfortunately they're just the led colors, we can't change them on this board

Hm, interesting, but in my case it doesn't fill the entire range while viocemeeter shows me that the signal in this channel clipping

I recorded the video, take a look on it pls
https://drive.google.com/file/d/15PpnbrATqmfq8o7kwXDQVAJ3XIVsxg_K/view?usp=sharing

**Comment by Golstrider** [comment]
@ollie-nye 

Already overloaded signal in Reaper, and send this signal to VoiceMeeter, and yes, it uses all segments but seems it scale uses Pre-Fader signal.  Is there any chance to see the post-fader signal on this scale??

**Comment by Golstrider** [comment]
Or I don't understand. The segment scale doesn't react to the fader moving if I use VB-Audio CABLE as an input.
But if I use the ASIO routing from Reaper to VoiceMeerer, seems it works fine.
But still, on the first bus, it works as the pre-fader signal scale. If I set up fader to +12 and have the overload in VoiceMeeter, the console still shows me that everything is ok

**Comment by ollie-nye** [comment]
So the meters should match what the meters do if you look at Voicemeeter itself, it's all on a linear scale though and the way Voicemeeter does the meter hold means that the first two or three bars will usually be on all the time because a signal rarely goes below -30dB. I don't think it should change depending on the input, we only listen to what Voicemeeter spits out the other end.

I might chop the bottom end off that scale, and spread the -30 to +10 range over all leds meaning each led would roughly be 5dB if that'd be better?
