### ISSUE TITLE
Behringer sometimes doesn't pick up fader info from VBAN

### ISSUE THREAD

**Issue by Golstrider** [ollie-nye/vban-xctrl#7]
At some times Behringer doesn't pick up faders info from VBAN (after starting or switching layer), so all mechanical faders became to -infinity position. So you should switch the layer to the next for forcible updating faders and then switch it back to move the for example mic fader.

**Comment by ollie-nye** [comment]
I've noticed this too, was caused by fixing the faders from always updating and 'chattering', should be able to sort it on first connect though, I'll take a look

**Comment by ollie-nye** [comment]
@Golstrider This should be sorted now, when the tool receives a connection from XTouch that's more than 5 seconds since the last one, we can assume it was disconnected. We can then force a fader refresh, so when it connects after a reboot it'll set every fader to their current level

**Comment by Golstrider** [comment]
@ollie-nye Thanks, updated! Works flawlessly.

I'm actually wondering, what about adding feedback for another button? For me, it will be very useful if the "select" button highlight works. For example, I use it to send the signal from the channel into B1(or 2 and 3) outputs. So when "select" is turned off I can monitor what is going on on this channel, then I can push the "select" button, and sound from this channel goes to the output bus. In this case, I don't have feedback, and I don't see if I sending the signal to the B bus or not. Sometimes I have confused about this, aha

If you can add this possibility at least for this button it will be very useful.

Also, I wish you a merry Christmas and a happy new year! Big thankful for your work!

**Comment by ollie-nye** [comment]
Hope you had a good holiday too! That's a good point, shouldn't be too bad to add either. I'll take a look this week for you and shout when it's updated

**Comment by Golstrider** [comment]
Thanks a lot! I'm looking forward! Do you have any Patreon page or PayPal? I want to make a donation, I really appreciate your work.

**Comment by Golstrider** [comment]
> Hope you had a good holiday too! That's a good point, shouldn't be too bad to add either. I'll take a look this week for you and shout when it's updated

Hi! It's been a few months, I wonder if you still working on this application?
Also, you said that you recoding the connection way, and will switch from VBAN to USB. I guess its a good idea because the mixer sometimes lost the connection while PC was overloaded due to shader compilation (video driver) and so on.
So I think the USB connection might be more stable
